---
- name: check if a reboot is needed
  stat: path=/var/run/reboot-required get_md5=no
  register: file
- name: restart machine
  command: shutdown -r now "Ansible updates triggered"
  async: 0
  poll: 0
  ignore_errors: true
  when: file.stat.exists == true
- name: wait for the machine to come back
  become: no
  local_action: wait_for host={{ inventory_hostname }} state=started
